projeto-csharp/mvcproject/mvcproject/Models/ErrorViewModel.cs
using System;

namespace mvcproject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

projeto-csharp/mvcproject/mvcproject/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvcproject.Models;

namespace mvcproject.Controllers
{
    public class GamesController : Controller
    {
        private readonly ILogger<GamesController> _logger;

        public GamesController(ILogger<GamesController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("jogos")]

        public IActionResult Games()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

projeto-csharp/mvcproject/mvcproject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvcproject.Models;

namespace mvcproject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("privacidade")]

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

projeto-csharp/mvcproject/mvcproject/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvcproject.Models;

namespace mvcproject.Controllers
{
    public class NewsController : Controller
    {
        private readonly ILogger<NewsController> _logger;

        public NewsController(ILogger<NewsController> logger)
        {
            _logger = logger;
        }

        [Route("noticias")]

        public IActionResult News()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

projeto-csharp/mvcproject/mvcproject/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using mvcproject.Models;

namespace mvcproject.Controllers
{
    public class SignupController : Controller
    {
        private readonly ILogger<SignupController> _logger;

        public SignupController(ILogger<SignupController> logger)
        {
            _logger = logger;
        }

        [Route("Cadastro")]

        public IActionResult Signup()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

projeto-csharp/mvcproject/mvcproject/Views/Games/Games.cshtml
@{
    ViewData["Title"] = "Jogos";
}
<div class="container" id="games-banner">
    <h1 class="text-center">Escolha o game que deseja visualizar.</h1>
</div>

projeto-csharp/mvcproject/mvcproject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="banner-image">
        <div class="container">

            <h1 class="text-light" id="home-h1">Jogos favoritos 2020</h1>

            <div class="col-6 float-left">
                <figure class="card" style="--bg-image-url: url();">
                    <img class="card__image" alt="Alt text here" src="~/img/card-rainbowsix.jpg">
                    <figcaption class="card__info">Tom clancy's: Rainbow Six Siege</figcaption>
                </figure>
            </div>

            <div class="col-6 float-right card-home">
                <figure class="card" style="--bg-image-url: url();">
                    <img class="card__image" alt="Alt text here" src="~/img/card_lol.jpg">
                    <figcaption class="card__info">League of Legends</figcaption>
                </figure>
            </div>

        </div>
    </div>
</div>

projeto-csharp/mvcproject/mvcproject/Views/News/News.cshtml
@{
    ViewData["Title"] = "Notícias";
}
<div class="container" id="banner">
    <h1 class="text-center">Novidades nos games</h1>
</div>

projeto-csharp/mvcproject/mvcproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - mvcproject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/lib/fontawesome/css/fontawesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fontawesome/css/brands.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fontawesome/css/solid.min.css">
    <link rel="stylesheet" type="text/css" href="~/lib/fontawesome/css/regular.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Grenze+Gotisch:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class=" navbar-nav navbar-toggleable-sm box-shadow">
            <div class="container">
                <aside class=" float-left mr-0 nav-torii">Torii Games</aside>
                <div class="float-left d-block mr-3" id="logo">
                    <a href="~/home" class="text-danger ">
                        @*<i class="fas fa-ankh"></i>*@
                        <i class="fas fa-torii-gate"></i>
                    </a>
                </div>

                <!-- Hamburguer -->
                <div class="d-none float-right" id="hamburg">
                    <img src="~/img/hamb.png">
                </div>

                <div class="links">
                        
                        <a class="nav-link d-block float-left" asp-area="" asp-controller="Home" asp-action="Index">Home</a>                   
                        <a class="nav-link d-block float-left" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>                       
                        <a class="nav-link d-block float-left" asp-area="" asp-controller="News" asp-action="News">Notícias</a>                      
                        <a class="nav-link d-block float-left" asp-area="" asp-controller="Games" asp-action="Games">Jogos</a>
                        <a class="nav-link d-block float-right" id="cadastro-nav" asp-area="" asp-controller="Signup" asp-action="Signup">Cadastre-se</a>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            <div class="text-center text-danger">
                &copy; 2020 - ToriiGames - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

projeto-csharp/mvcproject/mvcproject/Views/Signup/Signup.cshtml
@{
    ViewData["Title"] = "Cadastro";
}
<div class="container" id="banner">
    <h1 class="col-12 m-4 text-center">Faça seu cadastro para ter mais recursos no nosso site</h1>
</div>

<div class="contact" id="content-contact">

    <section>

        <div class="container">

            <div class="row">

                <!-- Formulário -->
                <div class="text-center col-5 float-right">

                    <form name="formContact">

                        <div class="form-group">
                            <label>Nome</label><br>
                            <input class="form-control" type="text" name="name" placeholder="Digite seu nome completo.">
                        </div>

                        <div class="form-group">
                            <label>E-mail</label><br>
                            <input class="form-control" type="email" name="email" placeholder="Digite seu E-mail.">
                        </div>

                        <div class="form-group">
                            <label>Telefone</label><br>
                            <input class="form-control" type="text" name="phone" placeholder="Digite seu número de telefone.">
                        </div>

                        <div class="form-group mb-5">
                            <label>Mensagem</label><br>
                            <textarea class="form-control" name="message" placeholder="Deixe o seu motivo para contato"></textarea>
                        </div>

                        <div class="form-group">
                            <div class="btn btn-secondary" id="btnSubmitContact">Enviar</div>
                        </div>

                    </form>

                </div>
                
            </div>

        </div>

    </section>

</div>